### ISSUE TITLE
Possibility to remove tag

### ISSUE THREAD

**Issue by d3xt3r2909** [Dn-a/flutter_tags#11]
It would be very good that there is a possibility to remove one tag (same as on InputTags with "x" button), but without an option, for a user to add new tags.

**Comment by Dn-a** [comment]
@d3xt3r2909 now you can create a popupmenu with the remove function

**Comment by d3xt3r2909** [comment]
Youp, but with popupmenu you have one additional tap for user

**Comment by Dn-a** [comment]
@d3xt3r2909 I will insert this feature in later versions

**Comment by Dn-a** [comment]
@d3xt3r2909  new version 0.4.2.
check and leave feedback
