### ISSUE TITLE
duplicate values in Textfield.

### ISSUE THREAD

**Issue by asapJ** [Dn-a/flutter_tags#13]
Entered values shows up twice on the textfield. 
But logging the content of my String array after onInsert callback, shows no duplicate values from the array.
N/B: duplicate is set to false too.

**Comment by Dn-a** [comment]
@asapJ please post your code

**Comment by Dn-a** [comment]
@asapJ Resolved?

**Comment by asapJ** [comment]
Yes,  Resolved.
I cloned the project,  made edits to InputTag and used my local copy.

**Comment by Dn-a** [comment]
@asapJ what was the problem?

**Comment by asapJ** [comment]
In the file input_tag.dart, 
In line 468, before adding the returned value to _tags,  I added a check to handle  if the _tags List already has the value being added, so there are no duplicates. For some reasons the operation of adding to _tags happens twice. 
I haven't gone back to look at the code to know why that is so, but adding that check solved this issue.  @Dn-a

**Comment by Dn-a** [comment]
@asapJ flutter version?

**Comment by gmkado** [comment]
Same issue and fix worked for me
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.6.3 at C:\Program Files\flutter
    • Framework revision bc7bc94083 (4 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

**Comment by Dn-a** [comment]
@gmkado @asapJ fixed in 0.3.2 version.
