### ISSUE TITLE
Read only tag

### ISSUE THREAD

**Issue by Gustavoaz** [Dn-a/flutter_tags#15]
I want a readonly tag, how i make this?

**Comment by Dn-a** [comment]
@Gustavoaz please give me more information...are you referring to a SelectableTags or InputTags?

**Comment by Gustavoaz** [comment]
@Dn-a SelectableTags, when user click I don't want that stay actived, my code:

`
_selectableTags
            .add(Tag(id: cnt, title: tag, active: false, icon: null));

SelectableTags(
            tags: _selectableTags,
            fontSize: widget.fontSize,
            symmetry: false,
            activeColor: Colors.lightBlue,
            color: Colors.white70,
            textActiveColor: Colors.white,
            borderSide: BorderSide(color: Colors.white70),
            backgroundContainer: Colors.transparent,
            textOverflow: TextOverflow.ellipsis,            
            onPressed: (tag) {}
          )`

**Comment by Dn-a** [comment]
@Gustavoaz ok, all or just some?

**Comment by Gustavoaz** [comment]
@Dn-a all

**Comment by Dn-a** [comment]
@Gustavoaz new version 0.4.2.
check and leave feedback.
