### ISSUE TITLE
InputTags class doesn't take inputDecoration into account while creating the input field

### ISSUE THREAD

**Issue by milosjovac** [Dn-a/flutter_tags#16]
To fix it, this line: https://github.com/Dn-a/flutter_tags/blob/20adfae6398eb775926ec607454f6d6659b8822e/lib/input_tags.dart#L473 should look like this:

```dart
inputDecoration: widget.inputDecoration ?? InputDecoration(
```

**Comment by Dn-a** [comment]
@milosjovac ok, thanks

**Comment by Vitaly-V** [comment]
[https://github.com/Dn-a/flutter_tags/pull/18](url)

**Comment by Dn-a** [comment]
@Vitaly-V ok merged.

**Comment by 7wonders** [comment]
Found a similar issue with the suggestions text style. Added pull request #20 to deal with it.
