### ISSUE TITLE
Could not read input channel file descriptors from parcel

### ISSUE THREAD

**Issue by jerinho** [Dn-a/flutter_tags#17]
> E/InputChannel-JNI(27717): Error 24 dup channel fd 0.
> E/MethodChannel#flutter/textinput(27717): Failed to handle method call
> E/MethodChannel#flutter/textinput(27717): java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
> E/MethodChannel#flutter/textinput(27717): 	at android.view.InputChannel.nativeReadFromParcel(Native Method)
> E/MethodChannel#flutter/textinput(27717): 	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
> E/MethodChannel#flutter/textinput(27717): 	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
> E/MethodChannel#flutter/textinput(27717): 	at android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
> E/MethodChannel#flutter/textinput(27717): 	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:62)
> E/MethodChannel#flutter/textinput(27717): 	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:102)
> E/MethodChannel#flutter/textinput(27717): 	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:99)
> E/MethodChannel#flutter/textinput(27717): 	at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInput(IInputMethodManager.java:664)
> E/MethodChannel#flutter/textinput(27717): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1280)
> E/MethodChannel#flutter/textinput(27717): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1167)
> E/MethodChannel#flutter/textinput(27717): 	at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:209)
> E/MethodChannel#flutter/textinput(27717): 	at io.flutter.plugin.editing.TextInputPlugin.onMethodCall(TextInputPlugin.java:61)
> E/MethodChannel#flutter/textinput(27717): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
> E/MethodChannel#flutter/textinput(27717): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
> E/MethodChannel#flutter/textinput(27717): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
> E/MethodChannel#flutter/textinput(27717): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#flutter/textinput(27717): 	at android.os.MessageQueue.next(MessageQueue.java:138)
> E/MethodChannel#flutter/textinput(27717): 	at android.os.Looper.loop(Looper.java:131)
> E/MethodChannel#flutter/textinput(27717): 	at android.app.ActivityThread.main(ActivityThread.java:5602)
> E/MethodChannel#flutter/textinput(27717): 	at java.lang.reflect.Method.invokeNative(Native Method)
> E/MethodChannel#flutter/textinput(27717): 	at java.lang.reflect.Method.invoke(Method.java:515)
> E/MethodChannel#flutter/textinput(27717): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
> E/MethodChannel#flutter/textinput(27717): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> E/MethodChannel#flutter/textinput(27717): 	at dalvik.system.NativeStart.main(Native Method)
> E/flutter (27717): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Could not read input channel file descriptors from parcel., null)
> E/flutter (27717): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
> E/flutter (27717): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
> E/flutter (27717): <asynchronous suspension>
> E/flutter (27717): #2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:410:36)
> E/flutter (27717): <asynchronous suspension>
> E/flutter (27717): #3      TextInputConnection.setEditingState (package:flutter/src/services/text_input.dart:637:30)
> E/flutter (27717): #4      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:847:10)
> E/flutter (27717): #5      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:862:7)
> E/flutter (27717): #6      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1103:5)
> E/flutter (27717): #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
> E/flutter (27717): #8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:103:5)
> E/flutter (27717): #9      FocusManager._update (package:flutter/src/widgets/focus_manager.dart:464:20)
> E/flutter (27717): #10     _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (27717): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (27717): #12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (27717): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (27717): #14     _rootRun (dart:async/zone.dart:1124:13)
> E/flutter (27717): #15     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (27717): #16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (27717): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (27717): #18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (27717): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by Dn-a** [comment]
@jerinho I don't think it's due to the plugin.
when does the error occur? if possible, post your code

**Comment by Dn-a** [comment]
@jerinho solved?
