### ISSUE TITLE
How to select a single item.

### ISSUE THREAD

**Issue by monxarat** [Dn-a/flutter_tags#2]
Hi guys,

How to select a single item.

**Comment by Dn-a** [comment]
be more specific ... are you referring to selectable tags or to Input Tags?

**Comment by monxarat** [comment]
I have used the selectable tag. I have not found any code handle this issue.

**Comment by Dn-a** [comment]
Have you tris this?
onPressed: (tag){
        print(tag.title);// tag object
    },

**Comment by monxarat** [comment]
What do you mean?
I want Single Selection(same Radiobutton group), not Multiselection(same CheckBox)

**Comment by Dn-a** [comment]
now it's clearer ... I'll implement this feature in future versions.
now you could do something like that: 
_singleCheck(Tag tag){
  _tags.where((tag) => tag.active).forEach((tag) {tag.active=false;}  ));
  tag.active=true;
}
//In onPressed method
onPressed:(tag){
_singleCheck(tag);
}
I have not tried it yet so I do not know if it works

**Comment by Dn-a** [comment]
@monxarat I added this feature in the new version 0.1.7.
I await your confirmation to close this issuse

**Comment by monxarat** [comment]
@Dn-a you can close this issue. But we should support choose the mode in the list.

**Comment by monxarat** [comment]
@Dn-a thank you very much
