### ISSUE TITLE
Feature request: Add option to have text field on separate row

### ISSUE THREAD

**Issue by 7wonders** [Dn-a/flutter_tags#21]
As mentioned in the title, it would be great to be able to have the text field for input tags on its own row with the tags above or below the field.

**Comment by Dn-a** [comment]
@7wonders sure, I'll add it in the next release!

**Comment by Dn-a** [comment]
@7wonders new version 0.4.2.
check and leave feedback

**Comment by moovida** [comment]
@Dn-a , does this mean you added the functionality? I was not able to have it on a different row.
It works at the begin, but after removing and adding some tags, new inserted tags appear in front of the textfield.

**Comment by Dn-a** [comment]
@moovida do you mean a textfield that occupies the whole line and with the possibility of inserting it at the beginning or at the end?

**Comment by moovida** [comment]
Actually I was thinking of a text field on top and all the tags added below it. Currently, when a new line is added, the tag is added at the begin of it, like in the below example when I add "add2" after the other 4:

![image](https://user-images.githubusercontent.com/390250/63143882-be767000-bff0-11e9-91f2-b2cc8200c82d.png)

I would rather have it appearing below the textfield. Actually I aslo tried after it, but couldn't find a a parameter  that would do that.

**Comment by Dn-a** [comment]
@moovida now it is clear to me ... try setting the width in TagsTextFiled.

`TagsTextFiled(width: 400)`

**Comment by moovida** [comment]
Ahh, that works indeed. It should be ok to set an extra large value in order to be on one line also on larger devices, right?

**Comment by Dn-a** [comment]
@moovida yes, overflow problems should not occur. however, in the next release I will put a specific parameter

**Comment by Dn-a** [comment]
@moovida did you solve with the width field?

**Comment by moovida** [comment]
@Dn-a , oh yes, sorry for not coming back to you on that. Thank you!

**Comment by Dn-a** [comment]
@moovida @7wonders  perfect! then I can close it
