### ISSUE TITLE
Purposes of popupMenuBuilder and popupMenuOnSelected on SelectableTags

### ISSUE THREAD

**Issue by alice-0-kim** [Dn-a/flutter_tags#22]
Hi! Please let me know if questions like this can be better answered elsewhere, but I was hoping to learn more about the purposes of **popupMenuBuilder** and **popupMenuOnSelected** on SelectableTags. What are the sole purposes of those and where can I see the examples/demos using such options? I noticed that the example snippet of code on README.md makes use of those options, but I simply do not see the differences with/without those options in my application. I read the documentation as well, but it simply says _Popup Menu Items_.

Any help would be appreciated. Thanks!

**Comment by Dn-a** [comment]
@alice-0-kim 
of the popupMenu generally you could do without it. it could be useful in particular cases, like the possibility to perform a specific function based on the text of the tag.

**Comment by alice-0-kim** [comment]
Thanks for taking the time to answer my question! Perhaps, is there a demo for that part specifically?

**Comment by Dn-a** [comment]
@alice-0-kim no but I could add some details in the future

**Comment by alice-0-kim** [comment]
That'll help a lot, thanks!
