### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by bingweibi** [Dn-a/flutter_tags#27]
How to make certain tags light at the beginning

**Comment by Dn-a** [comment]
@bingweibi Please provide more information

**Comment by bingweibi** [comment]
What I want to say is that some tags are active = true at the beginning, not all true or false.

**Comment by Dn-a** [comment]
@bingweibi for each tag you can decide whether it should be true or false. example with ternary operator
`active = ( i < 3 || i > 10 ? true : false);`

**Comment by bingweibi** [comment]
ok, thank you
