### ISSUE TITLE
CircleAvatar of image

### ISSUE THREAD

**Issue by SamadiPour** [Dn-a/flutter_tags#29]
image property is too much limited! it would be better if you change
```final ItemTagsImage image;```
to 
``` final widget image; ```
or at least put some option to enable/disable CircleAvatar!

thanks for your awesome library

**Comment by Dn-a** [comment]
@SamadiPour thanks for your feedback.
 I'll do my best in the next release.

**Comment by Dn-a** [comment]
@SamadiPour new release 0.4.4, check and leave feedback.
thanks

**Comment by SamadiPour** [comment]
@Dn-a 
Thanks for your support ❤️
