### ISSUE TITLE
The item in the first position is NULL.

### ISSUE THREAD

**Issue by monxarat** [Dn-a/flutter_tags#37]
When I get all items, the item at 0 is null.
`List<Item> lst = _tagStateKey.currentState?.getAllItem;`

<img width="480" alt="Screen Shot 2019-12-20 at 17 28 55" src="https://user-images.githubusercontent.com/4075787/71241175-5218ce00-234e-11ea-93c5-2409efb50385.png">

**Comment by Dn-a** [comment]
@monxarat I did some tests but I didn't find any side effects

**Comment by Dn-a** [comment]
@monxarat solved?
