### ISSUE TITLE
Sometimes there will be cases where the content is not fully displayed. .

### ISSUE THREAD

**Issue by LebenNNA** [Dn-a/flutter_tags#4]
Sometimes there will be cases where the content is not fully displayed. .

**Comment by Dn-a** [comment]
@LebenNNA please post your code here.

**Comment by LebenNNA** [comment]
These are my parameters
```dart
final List<String> _list = [
    '网易云',
    '拼多多',
    '美术',
    '互联网',
    '炫舞时代',
    '猫耳FM',
    '爱奇艺',
    '网易大神',
    '美容',
    '小红书',
    '同人文',
    '食物语',
    '篝火营地',
    '哔了狗了QP又不够了。。',
    '草丛三剑客',
    'Whose you daddy',
    'Black sheep wall',
    '上上下下左右左右ABBA',
  ];

  bool _symmetry = false;
  bool _singleItem = false;
  int _column = 10;
  double _fontSize = 14.0;

  Color _textColor = Color(0xff252c41);
  Color _selActiveColor = Color(0xfff75262);
  Color _allActiveColor = Color(0x80f75262);

  EdgeInsets _margin =
      const EdgeInsets.symmetric(horizontal: 10.0, vertical: 12.5);

  String _selectableOnPressed = '';

  List<Tag> _selectableTags = [];
  List<Tag> _selectedTags = [];

int index = 0;
    _list.forEach(
      (item) {
        _selectableTags.add(
          Tag(
            id: index,
            title: item,
            active: false,
          ),
        );
        index++;
      },
    );

SelectableTags(
      tags: _selectableTags,
      columns: _column,
      // textColor: _textColor,
      fontSize: _fontSize,
      symmetry: _symmetry,
      singleItem: _singleItem,
      activeColor: _allActiveColor,
      margin: _margin,
      boxShadow: [],
      onPressed: (tag) {
        setState(() {
          _selectableOnPressed = tag.toString();
          print('--------selectableOnPressed:$_selectableOnPressed--------');
          _selectableTags.remove(tag);
          _selectedTags.add(tag);
        });
      },
    );

```
This is the display effect
![ae04bb42-6ecb-483a-80e2-f29dd97bb93c](https://user-images.githubusercontent.com/15353971/53280394-8cc4d080-3754-11e9-8d16-7419d157e4f2.jpg)

I use the SelectableTags..

I have another problem. When the title is short enough, I find that each tag has a minimum width, not calculated based on the byte length of the title.
@Dn-a

**Comment by Dn-a** [comment]
@LebenNNA I will solve it in the next version (0.1.9).

**Comment by LebenNNA** [comment]
Ok, I am looking forward to it.

**Comment by LebenNNA** [comment]
I have another problem. When the title is short enough, I find that each tag has a minimum width, not calculated based on the byte length of the title.

And Can this problem be solved?
@Dn-a

**Comment by Dn-a** [comment]
@LebenNNA install version 0.2.0, take a test and let me know

**Comment by LebenNNA** [comment]
These are my code

**Comment by LebenNNA** [comment]
![04635131-49ff-40d8-857f-e0dc0334c6b0](https://user-images.githubusercontent.com/15353971/53539499-caf33300-3b4c-11e9-9aaa-b0b69f999700.jpg)
Sometimes there will be cases where the content is not fully displayed. . @Dn-a

**Comment by LebenNNA** [comment]
![qq 20190228113804](https://user-images.githubusercontent.com/15353971/53539671-77cdb000-3b4d-11e9-87ba-1e7dcb4529c5.png)

How can I set the tag to set its own length based on the length of the title?

**Comment by LebenNNA** [comment]
@Dn-a

**Comment by LebenNNA** [comment]
I guess the result is caused by the outlinebutton

**Comment by Dn-a** [comment]
@LebenNNA it's a problem I've encountered since the beginning, but I think I've found the solution...
Wait for the next version

**Comment by Dn-a** [comment]
@LebenNNA  
important update in the version 0.2.1
try it and let me know

**Comment by LebenNNA** [comment]
I still have a question, how to set the control fixed height vertically scrollable, or set only one line, then you can scroll horizontally @Dn-a

**Comment by monxarat** [comment]
In the `ListView` you can set `scrollDirection: Axis.horizontal` or `scrollDirection: Axis.vertical`

example: Create a listview holding list tag
```
                return ListView.separated(
                    scrollDirection: Axis.horizontal,
                    separatorBuilder: (context, index) => Divider(height: 50),
                    itemCount: snapshot.data.length,
                    itemBuilder: (BuildContext context, int index) {
                      ....
                      return <create List item>
                    });
```

**Comment by Dn-a** [comment]
@LebenNNA can i close the problem?

**Comment by LebenNNA** [comment]
ok, thank you
