### ISSUE TITLE
text field start

### ISSUE THREAD

**Issue by MihaelaTIMIS** [Dn-a/flutter_tags#40]
Is it possible to have the text field before tags ? 
I saw in demo that feature, but i can't find id in properties. 
Thanx

**Comment by Dn-a** [comment]
@MihaelaTIMIS of course, just use these parameters
```
Tags(
     verticalDirection: VerticalDirection.up ,
      textDirection: TextDirection.rtl ,
      .
      .
);
```

**Comment by MihaelaTIMIS** [comment]
And it worked! Thanks a lot 👍
