### ISSUE TITLE
How to restrict the row and enable vertical scroll 

### ISSUE THREAD

**Issue by maheshlalu** [Dn-a/flutter_tags#47]
How to restrict the row and enable vertical scroll after 3 rows.

**Comment by maheshlalu** [comment]
@Dn-a please help me out.

**Comment by kwent** [comment]
I would be interested by this feature as well !

**Comment by Dn-a** [comment]
@maheshlalu you should do it with customscrollview

**Comment by avi-yadav** [comment]
I just wrapped the `Tags` widget inside a `ListView` and gave only one child.
