### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by long1eu** [Dn-a/flutter_tags#48]
Hi!

Awesome package, but keep in mind that breaking changes should be handled with great care. Make sure you read the semantic versioning documentation. 
https://semver.org/

There is also a dart package that tells you the break breaking version that you should use when releasing a change like this in your api surface.
https://pub.dev/packages/pub_semver

**Comment by Dn-a** [comment]
@long1eu Thank you very much for the advice!

**Comment by long1eu** [comment]
No problem. Again, awesome work.
