### ISSUE TITLE
Input tags : Removing the last tag from the list throws IntegerDivisionByZeroException

### ISSUE THREAD

**Issue by monothorn** [Dn-a/flutter_tags#6]
To replicate,
Just keep on deleting the tags until you delete the last one.
Probable cause : onDelete doesn't check for tags list length before removing

Any way to prevent that?

**Comment by Dn-a** [comment]
@monothorn  please give the versiin

**Comment by monothorn** [comment]
Yeah doesnt seem to be an issue in the latest version
